Repository KU-CodiOn/CodiOn-Android, pull requests merged in 2025-05, with the labels that each got.

#9 [UI] 화면 ui
  app/src/main/java/com/konkuk/codion/ui/common/DropdownComponent.kt
  app/src/main/java/com/konkuk/codion/ui/common/TopAppBarComponent.kt
  app/src/main/java/com/konkuk/codion/ui/common/buttons/BigButtonWithIconComponent.kt
  app/src/main/java/com/konkuk/codion/ui/common/inputFields/InputFieldComponent.kt
  app/src/main/java/com/konkuk/codion/ui/common/inputFields/InputFieldWithBtnComponent.kt
  app/src/main/java/com/konkuk/codion/ui/common/modifier/ignoreTopPadding.kt
  app/src/main/java/com/konkuk/codion/ui/mypage/component/MypageMenuComponent.kt
  app/src/main/java/com/konkuk/codion/ui/mypage/component/ProfileBoxComponent.kt
  app/src/main/java/com/konkuk/codion/ui/mypage/dummy/ProfileDummyData.kt
  app/src/main/java/com/konkuk/codion/ui/mypage/screen/ChangePwdScreen.kt
  app/src/main/java/com/konkuk/codion/ui/mypage/screen/EditProfileScreen.kt
  app/src/main/java/com/konkuk/codion/ui/mypage/screen/MypageScreen.kt
  app/src/main/java/com/konkuk/codion/ui/onboarding/component/TermsBoxComponent.kt
  app/src/main/java/com/konkuk/codion/ui/onboarding/dummy/TermsDummyData.kt
  app/src/main/java/com/konkuk/codion/ui/onboarding/screen/FindPwdScreen.kt
  app/src/main/java/com/konkuk/codion/ui/onboarding/screen/LoginScreen.kt
  app/src/main/java/com/konkuk/codion/ui/onboarding/screen/RegisterMainScreen.kt
  app/src/main/java/com/konkuk/codion/ui/onboarding/screen/RegisterScreen.kt
  app/src/main/java/com/konkuk/codion/ui/onboarding/screen/RegisterWithEmailScreen.kt
  app/src/main/java/com/konkuk/codion/ui/onboarding/screen/ResetPwdScreen.kt
  app/src/main/java/com/konkuk/codion/ui/onboarding/screen/SplashScreen.kt
  app/src/main/java/com/konkuk/codion/ui/personalColor/component/ColorFeatureComponent.kt
  app/src/main/java/com/konkuk/codion/ui/personalColor/component/ColorGuidelineBoxComponent.kt
  app/src/main/java/com/konkuk/codion/ui/personalColor/component/ColorPaletteComponent.kt
  app/src/main/java/com/konkuk/codion/ui/personalColor/component/ColorResultTagLineComponent.kt
  app/src/main/java/com/konkuk/codion/ui/personalColor/component/CustomProgressBarComponent.kt
  app/src/main/java/com/konkuk/codion/ui/personalColor/dummy/ColorDummyData.kt
  app/src/main/java/com/konkuk/codion/ui/personalColor/screen/ColorCameraScreen.kt
  app/src/main/java/com/konkuk/codion/ui/personalColor/screen/ColorGuideScreen.kt
  app/src/main/java/com/konkuk/codion/ui/personalColor/screen/ColorResultScreen.kt
  app/src/main/res/drawable/ic_checkbox_selected.xml
  app/src/main/res/drawable/ic_checkbox_unselected.xml
  app/src/main/res/drawable/ic_eye_off.xml
  app/src/main/res/drawable/ic_eye_on.xml
  app/src/main/res/drawable/ic_mail.xml
  app/src/main/res/drawable/ic_mypage_arrow_right.xml
  app/src/main/res/drawable/img_color_autumn.png
  app/src/main/res/drawable/img_profile.png
  app/src/main/res/values/strings.xml
Labels: 🐶 지영, ✨ feat, 🎨 UI, 🩹 chore, 🍀 refactor

#11 [FEAT] 네비게이션 세팅 완료
  .idea/AndroidProjectSystem.xml
  .idea/compiler.xml
  .idea/encodings.xml
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/build.gradle.kts
  app/src/main/java/com/konkuk/codion/MainActivity.kt
  app/src/main/java/com/konkuk/codion/ui/codiRecord/component/CodiRecordEmpty.kt
  app/src/main/java/com/konkuk/codion/ui/codiRecord/navigation/CodiRecordNavigation.kt
  app/src/main/java/com/konkuk/codion/ui/codiRecord/screen/CodiRecordScreen.kt
  app/src/main/java/com/konkuk/codion/ui/codiRecord/screen/RegisterCodiCommentScreen.kt
  app/src/main/java/com/konkuk/codion/ui/common/BottomBarComponent.kt
  app/src/main/java/com/konkuk/codion/ui/common/ClothesCardComponent.kt
  app/src/main/java/com/konkuk/codion/ui/home/HomeScreen.kt
  app/src/main/java/com/konkuk/codion/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/com/konkuk/codion/ui/myCloset/navigation/MyClosetNavigation.kt
  app/src/main/java/com/konkuk/codion/ui/myCloset/screen/AddMyClothesDetailScreen.kt
  app/src/main/java/com/konkuk/codion/ui/myCloset/screen/AddMyClothesPictureScreen.kt
  app/src/main/java/com/konkuk/codion/ui/myCloset/screen/MyClosetScreen.kt
  app/src/main/java/com/konkuk/codion/ui/navigation/MainNavController.kt
  app/src/main/java/com/konkuk/codion/ui/navigation/MainNavHost.kt
  app/src/main/java/com/konkuk/codion/ui/navigation/MainTab.kt
  app/src/main/java/com/konkuk/codion/ui/navigation/MainTabRoute.kt
  app/src/main/java/com/konkuk/codion/ui/navigation/Routes.kt
  app/src/main/java/com/konkuk/codion/ui/navigation/component/MainBottomBar.kt
  app/src/main/java/com/konkuk/codion/ui/navigation/component/MainBottomBarItem.kt
  app/src/main/res/drawable/ic_closet.xml
  app/src/main/res/drawable/ic_codi_record.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_mypage.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 😽 나은, ✨ feat, ⚡️ fix, 🍀 refactor

#13 [FEAT] API 세팅 완료
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/konkuk/codion/CodiOnApp.kt
  app/src/main/java/com/konkuk/codion/MainActivity.kt
  app/src/main/java/com/konkuk/codion/data/di/NetworkModule.kt
  app/src/main/java/com/konkuk/codion/data/di/ServiceModule.kt
  app/src/main/java/com/konkuk/codion/data/dto/base/ApiResponseHandler.kt
  app/src/main/java/com/konkuk/codion/data/dto/base/BaseResponse.kt
  app/src/main/java/com/konkuk/codion/data/dto/request/LoginRequest.kt
  app/src/main/java/com/konkuk/codion/data/dto/response/LoginResponse.kt
  app/src/main/java/com/konkuk/codion/data/repository/AuthRepository.kt
  app/src/main/java/com/konkuk/codion/data/service/AuthService.kt
  app/src/main/java/com/konkuk/codion/ui/codiRecord/navigation/CodiRecordNavigation.kt
  app/src/main/java/com/konkuk/codion/ui/codiRecord/screen/CodiRecordScreen.kt
  app/src/main/java/com/konkuk/codion/ui/common/TopAppBarComponent.kt
  app/src/main/java/com/konkuk/codion/ui/common/TopAppBarState.kt
  app/src/main/java/com/konkuk/codion/ui/common/inputFields/InputFieldComponent.kt
  app/src/main/java/com/konkuk/codion/ui/home/HomeScreen.kt
  app/src/main/java/com/konkuk/codion/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/com/konkuk/codion/ui/myCloset/navigation/MyClosetNavigation.kt
  app/src/main/java/com/konkuk/codion/ui/myCloset/screen/AddMyClothesDetailScreen.kt
  app/src/main/java/com/konkuk/codion/ui/myCloset/screen/MyClosetScreen.kt
  app/src/main/java/com/konkuk/codion/ui/navigation/MainNavController.kt
  app/src/main/java/com/konkuk/codion/ui/navigation/MainNavHost.kt
  app/src/main/java/com/konkuk/codion/ui/navigation/Routes.kt
  app/src/main/java/com/konkuk/codion/ui/onboarding/navigation/OnboardingNavigation.kt
  app/src/main/java/com/konkuk/codion/ui/onboarding/screen/LoginScreen.kt
  app/src/main/java/com/konkuk/codion/ui/onboarding/screen/SplashScreen.kt
  app/src/main/java/com/konkuk/codion/ui/onboarding/state/LoginState.kt
  app/src/main/java/com/konkuk/codion/ui/onboarding/viewmodel/LoginViewModel.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 🐶 지영, ✨ feat, ⚡️ fix, 🩹 chore, 🍀 refactor
